services:
  ra-sandbox:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ra/sandbox
    container_name: ra-sandbox
    env_file: .env
    ports:
      - 5173:5173
    tty: true
    volumes:
      - .:/usr/src/app
    command: ["bash"]
